config/routes.rb
Fondak::Application.routes.draw do

  match 'photo' => 'home#photo'
  match 'rules' => 'home#rules'
  match 'discusion' => 'home#discusion'
  match 'history' => 'home#history'
  match 'teams_men' => 'home#teams_men'
  match 'teams_women' => 'home#teams_women'
  
  match 'schedule_friday' => 'home#schedule_friday'
  match 'schedule_saturday' => 'home#schedule_saturday'
  match 'schedule_tuesday' => 'home#schedule_tuesday'

  match 'contact' => 'home#contact'

  match 'photo_2014' => 'home#photo_2014'
  match 'photo_2013' => 'home#photo_2013'
  match 'photo_2012' => 'home#photo_2012'

  resources :home do
    get 'set_locale', :on => :collection
  end

  root :to => 'home#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  before_filter :locale_setter

  def locale_setter
    binding
    I18n.locale = params[:locale] #|| I18n.default_locale
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end

end

app/controllers/home_controller.rb
# encoding: utf-8

class HomeController < ApplicationController

  def index
    carousel_images = *(1..30)
    @picked_images = carousel_images.sample(10)
    puts params[:action]

    @locale=params[:locale]
  end

  def rules

  end

  def photo

  end

  def history

  end

  def schedule_friday

  end

  def schedule_saturday

  end

  def schedule_tuesday

  end

  def teams_men
    @teams=[]
    team=[]

    File.open("data/teams_men_2015.data", "r") do |file|
      file.each_line do |line|
        if line == "-\n"
          @teams << team
          team.each do |p|
          end
          team = []
        else
          team << line.force_encoding("UTF-8").gsub('\n','')
        end
      end

    end
  end

  def teams_women
    @teams=[]
    team=[]

    File.open("data/teams_women_2015.data", "r") do |file|
      file.each_line do |line|
        
        if line == "-\n"
          @teams << team
          team.each do |p|
          end
          team = []
        else
          team << line.force_encoding("UTF-8").gsub('\n','')
        end
      end
    end
  end

  def contact

  end

  def locales
  end

  def set_locale
    I18n.locale = params[:locale]
    redirect_to home_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/contact.haml
%section
	/ SECOND BLOCK
	#contact1-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%article.s-3.l-2.font-comforta
							%img.organizer1{:src => "/assets/jakubko.png"}

						%article.s-9.l-6.font-comforta
							.about
								%h2 Jakub Jurč
								%h4 
									= t('contact')
								%ul
									%li 
										Mobil:
										+421 902 322 133
									%li 
										Mail:
										meniscusjlf@gmail.com
									%li
										= t('room')
										608

	#contact2-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%article.s-3.l-2.font-comforta
							%img.organizer2{:src => "/assets/haiko.png"}

						%article.s-9.l-6.font-comforta
							.about
								%h2 Heiko Pedan
								%h4
									= t('contact')
								%ul
									%li 
										Mobil:
										-
									%li 
										Mail:
										meniscusjlf@gmail.com
									%li
										= t('room')
										-

app/views/home/history.haml
.container.history
	.row
		.col-xs-18.col-sm-12
			%p.title Historia hokejbalu na JLF UK
			.text
	.row
		.col-xs-12.col-sm-8
			.text-first
				%p Celé sa to začalo niekedy na jeseň roku 1992, v období, ktoré sa tak ako celý začiatok 90. rokov na JLF UK nieslo v znamení bujarého spoločenského života a o to skromnejších športových aktívít.
				%p Významný zvrat v tomto trende priniesli študenti, ktorí k nám prestúpili z LF Hradec Kralové a boli v minulosti aktívni hokejisti.
		.col-xs-6.col-sm-4
			#fade.first
				%img.woman-team{:src => "/assets/history/woman-team.jpg"}
				%img.team4{:src => "/assets/history/team4.jpg"}
				%img.men{:src => "/assets/history/men.jpg"}

	.row
		.col-xs-6.col-sm-4
			#fade.second
				%img.cup-small{:src => "/assets/history/cup-small.jpg"}
				%img.match{:src => "/assets/history/match.jpg"}
				%img.cup2{:src => "/assets/history/cup2.jpg"}

		.col-xs-12.col-sm-8
			.text-second
				%p Vyzvali slovenských študentov, či by si nešli zahrať. Bolo ich asi 10. Po tejto skúsenosti skrsla myšlienka zahrať si hokejbalový turnaj.
				%p 19.3 1993 sa konal I. hokejbalový turnaj O putovný fonendoskop JLF UK Martin. Hlavnou cenou pre víťaza bol každoročne „putovný martinský fonendoskop“, ktorý bol zhotovený z červených gumených hadičiek, slúchadiel a lievika. Na fonendoskop sa každoročne pripísal názov víťazného klubu a iniciálky hráčov.
	.row
		.col-xs-9.col-sm-6
			.text-third
				%p Na prvom ročníku hralo 6 tímov, každým rokom pribúdali nové a nové.
				%p V roku 1997 sa uskutočnil na pôde JLF UK prvý ročník Martinského Fonendoskopu.
				%p V roku 2013 sa na XVII. Martinskom Fonendoskope zúčastnilo 28 tímov z toho 20 mužských a 8 ženských, ktorí prichádzajú nie len zo Slovenska ale taktiež aj z Českej republiky.
		.col-xs-9.col-sm-6
			#fade.third
				%img.team2{:src => "/assets/history/team2.jpg"}
				%img.cup{:src => "/assets/history/cup.jpg"}
				%img.team3{:src => "/assets/history/team3.jpg"}

	.row
		.col-xs-6.col-sm-4
			#fade.forth
				%img.team{:src => "/assets/history/team.jpg"}
				%img.gipsy{:src => "/assets/history/gipsy.jpg"}
				%img.gipsy{:src => "/assets/history/woman-team-2.jpg"}
		.col-xs-12.col-sm-8
			.text-forth
				%p K samotnému turnuja patrí aj sprievodná akcia, koncerty, ktoré sa uskutočňujú na Študentskom domove JLF UK
				%p Minulý rok sa o zábavu postarali DJ Syky, Labužníci, IntrakBand a prekvapenie sobotňajšieho večera Gipsy čave.

app/views/home/index.haml
%section
	/ CAROUSEL
	#carousel
		#owl-demo.owl-carousel.owl-theme
			.item
				= image_tag "1.jpg", :class => "main_photo"
				.line
			.item
				= image_tag "2.jpg", :class => "main_photo"
				.line
			.item
				= image_tag "3.jpg", :class => "main_photo"
				.line
			.item
				= image_tag "4.jpg", :class => "main_photo"
				.line
			.item
				= image_tag "5.jpg", :class => "main_photo"
				.line
			.item
				= image_tag "6.jpg", :class => "main_photo"
				.line



	/ SECOND BLOCK
	#second-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%h1 
							= t('title1')
						%p.info 
							= t('title2')
						%br
						%p.info 
							= t('title3')

	#third-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%h1 
							= t('countdown')
						%center
							.countdown.styled

	#fourth-block
		.line
			.margin
				%article.s-3.l-1.center
					.item
						= link_to "https://www.facebook.com/events/977373485608196/" do
							= image_tag("facebook.png", :class => "fb")


	/ / GALLERY CAROUSEL
	/ #third-block
	/ 	.line
	/ 		%h2 Gallery
	/ 		.margin
	/ 			.s-12.l-3
	/ 				= image_tag "img/330x190.jpg"
	/ 			.s-12.l-3
	/ 				= image_tag "img/330x190-2.jpg"
	/ 			.s-12.l-3
	/ 				= image_tag "img/330x190-3.jpg"
	/ 			.s-12.l-3
	/ 				= image_tag "img/330x190.jpg"


	/ #fourth-block
	/ 	.line
	/ 		#owl-demo2.owl-carousel.owl-theme
	/ 			.item
	/ 				%h2 Amazing responsive template
	/ 				%p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet 	            dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit 	            lobortis nisl ut aliquip ex ea commodo consequat.
	/ 			.item
	/ 				%h2 Responsive components
	/ 				%p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet 	            dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit 	            lobortis nisl ut aliquip ex ea commodo consequat.
	/ 			.item
	/ 				%h2 Retina ready
	/ 				%p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet 	            dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit 	            lobortis nisl ut aliquip ex ea commodo consequat.

app/views/home/photo.haml
.container.photo
	.row
		.col-xs-18.col-sm-12
			.col-xs-12.col-sm-8.col-xs-offset-4.col-sm-offset-2
				%ul.nav.nav-tabs#myTab
					%li.active
						%a{"data-toggle" => "tab", :href => "#2013"} 2013
					%li
						%a{"data-toggle" => "tab", :href => "#2012"} 2012
					%li
						%a{"data-toggle" => "tab", :href => "#2011"} 2011
					%li
						%a{"data-toggle" => "tab", :href => "#2010"} 2010
					%li
						%a{"data-toggle" => "tab", :href => "#2009"} 2009

			.tab-content
				#2013.tab-pane.active
					.col-xs-4.col-sm-3.first
						- [6,10,14,18,22,26,30].each do |i|
							%a.fancybox{:href => "assets/2013/0-#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2013/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [7,11,15,23,27,31,35].each do |i|
							%a.fancybox{:href => "assets/2013/0-#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2013/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [8,12,16,20,24,28,32].each do |i|
							%a.fancybox{:href => "assets/2013/0-#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2013/00-#{i}.jpg"}

					.col-xs-4.col-sm-3.last
						- [9,13,17,21,25,29,33].each do |i|
							%a.fancybox{:href => "assets/2013/0-#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2013/00-#{i}.jpg"}

				#2012.tab-pane
					.col-xs-4.col-sm-3.first
						- [6,10,14,18,22,26,30,38,42,46].each do |i|
							%a.fancybox{:href => "assets/2012/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2012/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [7,11,15,23,27,31,35,39,43,47].each do |i|
							%a.fancybox{:href => "assets/2012/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2012/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [8,12,16,20,24,28,32,36,40,44].each do |i|
							%a.fancybox{:href => "assets/2012/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2012/00-#{i}.jpg"}

					.col-xs-4.col-sm-3.last
						- [9,13,17,21,25,29,33,37,41,45].each do |i|
							%a.fancybox{:href => "assets/2012/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2012/00-#{i}.jpg"}

				#2011.tab-pane

				#2010.tab-pane
					.col-xs-4.col-sm-3.first
						- [1,5,9,13,17,21,25,29,33,37,41,45].each do |i|
							%a.fancybox{:href => "assets/2010/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2010/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [2,6,10,14,18,22,26,30,38,42,46].each do |i|
							%a.fancybox{:href => "assets/2010/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2010/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [3,7,11,15,23,27,31,35,39,43,47].each do |i|
							%a.fancybox{:href => "assets/2010/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2010/00-#{i}.jpg"}

					.col-xs-4.col-sm-3.last
						- [4,8,12,16,20,24,28,32,36,40,44].each do |i|
							%a.fancybox{:href => "assets/2010/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2010/00-#{i}.jpg"}

				#2009.tab-pane
					.col-xs-4.col-sm-3.first
						- [1,5,9,13,17,21,25,29,33,37].each do |i|
							%a.fancybox{:href => "assets/2009/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2009/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [2,6,10,14,18,22,26,30,38,42].each do |i|
							%a.fancybox{:href => "assets/2009/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2009/00-#{i}.jpg"}

					.col-xs-4.col-sm-3
						- [3,7,11,15,23,27,31,35,39,41].each do |i|
							%a.fancybox{:href => "assets/2009/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2009/00-#{i}.jpg"}

					.col-xs-4.col-sm-3.last
						- [4,8,12,16,20,24,28,32,36,40].each do |i|
							%a.fancybox{:href => "assets/2009/#{i}.jpg", :rel => "group"}
								%center
									%img{:alt => "", :src => "assets/2009/00-#{i}.jpg"}

app/views/home/photo_2012.haml
#third-block.font-comforta
	.line
		%h2 Galéria 2012
		- (1..7).each do |i|
			.margin
				- (1..4).each do |ii|
					.s-12.l-3
						%a.fancybox{:href => "assets/2012/#{ii+((i-1)*4)}.jpg", :rel => "group"}
							%center
								= image_tag "2012/#{ii+((i-1)*4)}_s.jpg"
		.margin
			.s-12.l-3
				%a.fancybox{:href => "assets/2012/29.jpg", :rel => "group"}
					%center
						= image_tag "2012/29_s.jpg"
			.s-12.l-3
				%a.fancybox{:href => "assets/2012/30.jpg", :rel => "group"}
					%center
						= image_tag "2012/30_s.jpg"

/ #third-block.font-comforta
/ 	.line
/ 		%h2 Galléria 2012
/ 		.margin
/ 			.s-12.l-3
/ 				= image_tag "img/330x190.jpg"
/ 			.s-12.l-3
/ 				= image_tag "img/330x190-2.jpg"
/ 			.s-12.l-3
/ 				= image_tag "img/330x190-3.jpg"
/ 			.s-12.l-3
/ 				= image_tag "img/330x190.jpg"

app/views/home/photo_2013.haml
#third-block.font-comforta
	.line
		%h2 Galéria 2013
		- (1..9).each do |i|
			.margin
				- (1..4).each do |ii|
					.s-12.l-3
						%a.fancybox{:href => "assets/2013/#{ii+((i-1)*4)}.jpg", :rel => "group"}
							%center
								= image_tag "2013/#{ii+((i-1)*4)}_s.jpg"

app/views/home/photo_2014.haml
#third-block.font-comforta
	.line
		%h2 Galéria 2014
		- (1..8).each do |i|
			.margin
				- (1..4).each do |ii|
					.s-12.l-3
						%a.fancybox{:href => "assets/2014/#{ii+((i-1)*4)}.jpg", :rel => "group"}
							%center
								= image_tag "2014/#{ii+((i-1)*4)}_s.jpg"

app/views/home/rules.haml
%section
	/ SECOND BLOCK
	#rules1-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%h1 
							= t('rules')
						%h3.rules
							= t('rules1')
						%ul
							%li
								= t('rules11')
							%li
								= t('rules12')
							%li
								= t('rules13')
							%li
								= t('rules14')
							%li
								= t('rules15')
							%li
								= t('rules16')
							%li
								= t('rules17')
	#rules2-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%h3.rules
							= t('rules2')
						%ul
							%li
								= t('rules21')
							%li
								= t('rules22')
							%li
								= t('rules23')
	#rules3-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%h3.rules
							= t('rules3')
						%ul
							%li
								= t('rules31')
							%li
								= t('rules32')
							%li
								= t('rules33')
							%li
								= t('rules34')

app/views/home/schedule_friday.haml
%section
	#schedule1-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%center
							%h1
								= t('friday')
						%h3 
							= t('field')
							1
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 14:10
									%td Hltači Ohňa
									%td Paris Aint German
									%td
								%tr
									%td 14:50
									%td BanterBhais
									%td Icelandicks
									%td
								%tr
									%td 15:30
									%td Hltači Ohňa
									%td Pimp Squad
									%td
								%tr
									%td 16:10
									%td Mrkvičky
									%td THE ANGRY GLUTES
									%td
								%tr
									%td 16:50
									%td Spotená Božena
									%td Scousers
									%td
								%tr
									%td 17:30
									%td Icelandicks
									%td Paris Aint German
									%td
								%tr
									%td 18:10
									%td THE ANGRY GLUTES
									%td Multiple Scorgasms
									%td
								%tr
									%td 18:50
									%td BanterBhais
									%td Pimp Squad
									%td
						.space
						%h3 
							= t('field')
							2
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 14:10
									%td Red Stars Martin
									%td RumBull
									%td
								%tr
									%td 14:50
									%td Fraukes‘ Boys
									%td Scousers
									%td
								%tr
									%td 15:30
									%td FC Koniferum
									%td Red Stars Martin
									%td
								%tr
									%td 16:10
									%td Estrogen United
									%td Studené Pipäty
									%td
								%tr
									%td 16:50
									%td TJ Mordor
									%td RumBull
									%td
								%tr
									%td 17:30
									%td XY
									%td Fraukes‘ Boys
									%td
								%tr
									%td 18:10
									%td Atrofia mammae
									%td Estrogen United
									%td
								%tr
									%td 18:50
									%td YMCA
									%td Red Stars Martin
									%td

app/views/home/schedule_saturday.haml
%section
	#schedule2-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%center
							%h1
								= t('saturday')
						%h3 
							= t('field')
							1
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 9:00
									%td Icelandicks
									%td Pimp Squad
									%td
								%tr
									%td 9:40
									%td Spotená Božena
									%td Fraukes’ Boys
									%td
								%tr
									%td 10:20
									%td BanterBhais
									%td Hltači Ohňa
									%td
								%tr
									%td 11:00
									%td Multiple Scorgasms
									%td Mrkvičky
									%td
								%tr
									%td 11:40
									%td Pimp Squad
									%td Paris Aint German
									%td
								%tr
									%td 12:20
									%td Paris Aint German
									%td BanterBhais
									%td
								%tr
									%td 13:00
									%td Atrofia mammae
									%td Estrogen United
									%td
								%tr
									%td 13:40
									%td TJ Mordor
									%td Red Stars Martin
									%td
								%tr
									%td 14:20
									%td RumBull
									%td YMCA
									%td
						.space
						%h3 
							= t('field')
							2
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 9:00
									%td YMCA
									%td TJ Mordor
									%td
								%tr
									%td 9:40
									%td Scousers
									%td XY
									%td
								%tr
									%td 10:20
									%td RumBull
									%td FC Koniferum
									%td
								%tr
									%td 11:00
									%td Studené Pipäty
									%td Atrofia mammae
									%td
								%tr
									%td 11:40
									%td TJ Mordor
									%td FC Koniferum
									%td
								%tr
									%td 12:20
									%td XY
									%td Spotená Božena
									%td
								%tr
									%td 13:00
									%td FC Koniferum
									%td YMCA
									%td
								%tr
									%td 13:40
									%td 
										= t('match1')
										%br
										A3-B3 
										= t('match11')
									%td 
									%td
								%tr
									%td 14:20
									%td 
										= t('match2')
										1
										%br
										A1-B2 
										= t('match22')
									%td 
									%td

	#schedule1-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%center
							%h1
								= t('saturday')
						%h3 
							= t('field')
							1
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 
									%td
										= t('quarter')
									%td
										= t('quarter')
									%td
								%tr
									%td 15:00
									%td C1
									%td B3
									%td G
								%tr
									%td 15:40
									%td A2
									%td 
										= t('betterFrom')
										B2/C2
									%td H
								%tr
									%td 16:20
									%td 
										= t('match2')
										2
									%td 
									%td
								%tr
									%td 17:00
									%td 
										= t('semi')
										%br
										G
									%td
										= t('semi')
										%br
										H
									%td
								%tr
									%td 17:40
									%td 
										= t('match2')
										1
									%td
										A1-B2
										= t('match22')
									%td

						.space
						%h3 
							= t('field')
							2
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 
									%td
										= t('quarter')
									%td
										= t('quarter')
									%td
								%tr
									%td 15:00
									%td B1
									%td C3
									%td I
								%tr
									%td 15:40
									%td A1
									%td 
										= t('worseFrom')
										B2/C2
									%td J
								%tr
									%td 16:20
									%td 
										= t('match1')
										%br
										A3-B3
										= t('match22')
									%td 
									%td
								%tr
									%td 17:00
									%td 
										= t('semi')
										%br
										I
									%td
										= t('semi')
										%br
										J
									%td
								%tr
									%td 17:40
									%td 
										= t('semiW')
										2
										%br
										B1-A2
										= t('match22')
									%td
									%td

app/views/home/schedule_tuesday.haml
%section
	#schedule2-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%center
							%h1
								= t('tuesday')
						%h3 
							= t('field')
							1
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 16:50
									%td 
										= t('3placeMen')
									%td
								%tr
									%td 17:30
									%td 
										= t('3placeWomen')
									%td
	
						%h3 
							= t('field')
							1
						%table
							%thead
								%tr
									%th 
										= t('time')
									%th
										= t('team')
									%th
										= t('result')
							%tbody
								%tr
									%td 16:50
									%td 
										= t('finalMen')
									%td
								%tr
									%td 17:30
									%td 
										= t('finalWomen')
									%td
	

app/views/home/teams_men.haml
# encoding: utf-8

- @teams.each do |team|
	#teams1-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%table
							%thead
								%tr
									%th 
										= team[0]
							%tbody
								- team[1..-1].each do |player|
									%tr
										%td 
											= player


/ #teams2-block
/ 	.line
/ 		.margin-bottom
/ 			.margin
/ 				%article.s-12.l-8.center.font-comforta
/ 					%table
/ 						%thead
/ 							%tr
/ 								%th #
/ 								%th TJ Mordor
/ 						%tbody

app/views/home/teams_women.haml
# encoding: utf-8

- @teams.each do |team|
	#teams2-block
		.line
			.margin-bottom
				.margin
					%article.s-12.l-8.center.font-comforta
						%table
							%thead
								%tr
									%th 
										= team[0]
							%tbody
								- team[1..-1].each do |player|
									%tr
										%td 
											= player

app/views/layouts/application.haml
!!!
%html
	%head
		%meta{:content => "width=device-width; initial-scale=1.0", :name => "viewport"}
		%meta(http-equiv="Content-Type" content="text/html; charset=UTF-8")
		%title Meniscus Cup
		= favicon_link_tag 'favicon.png'
		= stylesheet_link_tag    "application"
		= javascript_include_tag "application"
		= csrf_meta_tags


	%body.size-1140
		/ TOP NAV WITH LOGO
		%header
			%nav
				.line
					.s-12.l-2
						= link_to root_path do
							= image_tag "logo.png", :class => "logo"
					.top-nav.s-12.l-10.right
						%p.nav-text Custom menu text
						%ul.right
							%li
								= link_to root_path do 
									= t('main')
							%li
								%a 
									= t('schedule')
								%ul
									%li
										= link_to schedule_friday_path do
											= t('friday')
											24.4. 2015
									%li
										= link_to schedule_saturday_path do
											= t('saturday')
											25.4. 2015
									%li
										= link_to schedule_tuesday_path do
											= t('tuesday')
											28.4. 2015

							%li.teams
								%a
									= t('teams')
								%ul
									%li
										= link_to teams_men_path do
											= t('teams_men')
									%li
										= link_to teams_women_path do
											= t('teams_women')
							%li
								%a 
									= t('gallery')
								%ul
									%li
										= link_to "Meniscus Cup 2014", photo_2014_path
									%li
										= link_to "Meniscus Cup 2013", photo_2013_path
									%li
										= link_to "Meniscus Cup 2012", photo_2012_path
							%li
								= link_to rules_path do
									= t('rules')
							%li
								= link_to contact_path do
									= t('contact')
							%li
								- if @locale == "en" 
									= link_to set_locale_home_index_path(:locale => :sk), :class => "flag" do
										= image_tag 'flag-sk.png', :class => "flag"
								- else
									= link_to set_locale_home_index_path(:locale => :en), :class => "flag" do
										= image_tag 'flag-uk.png', :class => "flag"

		= yield